# docker-compose.yml

version: '3'

services: 
  php:
    image: "php:apache"
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
    volumes:
      - "./src:/var/www/html"
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    